spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/smart_food
    username: nss
    password: nss
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083