services:
  postgres:
    image: postgres:16
    container_name: nss-postgres

    environment:
      POSTGRES_DB: smart_food
      POSTGRES_USER: nss
      POSTGRES_PASSWORD: nss

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: