# 1. THE DEPLOYMENT (The Manager)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  # I want exactly 1 running copy for now
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: vmtoriia/my-order-service:1.0
          ports:
            - containerPort: 8082
          # I am injecting the new database coordinates here
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/order_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin

---
# 2. THE SERVICE (The Network Hub)

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082