# 1. THE DEPLOYMENT (The Database Manager)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          # These environment variables initialize the database!
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: order_db

---
# 2. THE SERVICE (The Internal Network Hub)
apiVersion: v1
kind: Service
metadata:
  #This becomes the DNS hostname inside the cluster.
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432